### ISSUE TITLE
3.7.0 seems broken

### ISSUE THREAD

**Issue by boxed** [HubSpot/hubspot-api-python#39]
I had a non-pinned dependency, so I ran tests just now and got this big crash in tests:

```
Internal Server Error: /prospects/1/edit/1/data/
Traceback (most recent call last):
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 545, in resolve
    for pattern in self.url_patterns:
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/boxed/Projects/dryft/dryft/urls.py", line 22, in <module>
    path('integrations/', include('dryft.integrations.urls')),
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/boxed/Projects/dryft/dryft/integrations/urls.py", line 10, in <module>
    path('hubspot/', include('dryft.integrations.hubspot.urls')),
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/boxed/Projects/dryft/dryft/integrations/hubspot/urls.py", line 2, in <module>
    from . import views
  File "/Users/boxed/Projects/dryft/dryft/integrations/hubspot/views.py", line 3, in <module>
    from hubspot import HubSpot
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/hubspot/__init__.py", line 1, in <module>
    from .client import Client
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/hubspot/client.py", line 5, in <module>
    from .discovery.conversations.discovery import Discovery as ConversationsDiscovery
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/hubspot/discovery/conversations/discovery.py", line 2, in <module>
    from .visitor_identification.discovery import Discovery as VisitorIdentificationDiscovery
  File "/Users/boxed/Projects/dryft/venv/lib/python3.8/site-packages/hubspot/discovery/conversations/visitor_identification/discovery.py", line 1, in <module>
    import hubspot.conversations.visitor_identification as api_client
ModuleNotFoundError: No module named 'hubspot.conversations'
```

I've worked around it for now by pinning to 3.6.1

**Comment by plaurynovich-hubspot** [comment]
Hi, thank you. It should be fixed in 3.7.1.
