### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by davidkong0987** [HubSpot/hubspot-api-python#63]
----> 16 from hubspot import HubSpot

ImportError: cannot import name 'HubSpot' from 'hubspot'

**Comment by plaurynovich-hubspot** [comment]
Hi, @davidkong0987. Could you provide more details, please? It might be useful to know a version the sdk that you use. Thank you.

**Comment by davidkong0987** [comment]
hey - does this help?
```
(base) MacBook-Pro-5:emails apple$ pip install hubspot-api-client
Requirement already satisfied: hubspot-api-client in /Users/apple/anaconda3/lib/python3.7/site-packages (3.8.2)
Requirement already satisfied: six>=1.10 in /Users/apple/anaconda3/lib/python3.7/site-packages (from hubspot-api-client) (1.13.0)
Requirement already satisfied: python-dateutil in /Users/apple/anaconda3/lib/python3.7/site-packages (from hubspot-api-client) (2.8.1)
Requirement already satisfied: urllib3>=1.15 in /Users/apple/anaconda3/lib/python3.7/site-packages (from hubspot-api-client) (1.25.7)
Requirement already satisfied: certifi in /Users/apple/anaconda3/lib/python3.7/site-packages (from hubspot-api-client) (2020.12.5)
```

**Comment by plaurynovich-hubspot** [comment]
Do you reproduce it in the python shell? Or is there any steps to reproduce the error?

**Comment by davidkong0987** [comment]
```
(base) MacBook-Pro-5:emails apple$ python hubspot.py
Traceback (most recent call last):
  File "hubspot.py", line 2, in <module>
    from hubspot import HubSpot
  File "/.../hubspot.py", line 2, in <module>
    from hubspot import HubSpot
ImportError: cannot import name 'HubSpot' from 'hubspot' (/Users/apple/Google Drive/sommpyfiles/emails/hubspot.py
```

**Comment by plaurynovich-hubspot** [comment]
Thank you, @davidkong0987. Could you rename your file from hubspot.py to something else?

**Comment by davidkong0987** [comment]
Thank you so much :D
