### ISSUE TITLE
3.7.0 Initial import fails - dateparser throws syntax invalid alert. 

### ISSUE THREAD

**Issue by HectorGit** [HubSpot/hubspot-api-python#65]
Hi ! Thanks for making this package. 

I've installed hubspot-api-client via pip 
Using Python 3.7.0

I've added the line :

from hubspot import HubSpot

And I'm receiving this error. I'm unsure what the problem with dateutil is. 

Traceback (most recent call last):
  File "C:\Users\Hector\Documents\ergonomyx\ergonomyx-ecommerce\ergonomyx.py", line 15, in <module>
    from app import app
  File "C:\Users\Hector\Documents\ergonomyx\ergonomyx-ecommerce\app\__init__.py", line 310, in <module>
    from app import routes, models, errors, admin_center, ajax_handlers, assets, login_register, tax_helpers, gtag_helpers
  File "C:\Users\Hector\Documents\ergonomyx\ergonomyx-ecommerce\app\routes.py", line 38, in <module>
    from hubspot import HubSpot
  File "c:\users\hector\documents\ergonomyx\ergonomyx-ecommerce\venv\lib\site-packages\hubspot\__init__.py", line 1, in <module>
    from .client import Client
  File "c:\users\hector\documents\ergonomyx\ergonomyx-ecommerce\venv\lib\site-packages\hubspot\client.py", line 2, in <module>
    from .discovery.auth.discovery import Discovery as AuthDiscovery
  File "c:\users\hector\documents\ergonomyx\ergonomyx-ecommerce\venv\lib\site-packages\hubspot\discovery\auth\discovery.py", line 1, in <module>
    from .oauth.discovery import Discovery as OAuthDiscovery
  File "c:\users\hector\documents\ergonomyx\ergonomyx-ecommerce\venv\lib\site-packages\hubspot\discovery\auth\oauth\discovery.py", line 1, in <module>
    import hubspot.auth.oauth as api_client
  File "c:\users\hector\documents\ergonomyx\ergonomyx-ecommerce\venv\lib\site-packages\hubspot\auth\oauth\__init__.py", line 20, in <module>
    from hubspot.auth.oauth.api.default_api import DefaultApi
  File "c:\users\hector\documents\ergonomyx\ergonomyx-ecommerce\venv\lib\site-packages\hubspot\auth\oauth\api\__init__.py", line 6, in <module>
    from hubspot.auth.oauth.api.default_api import DefaultApi
  File "c:\users\hector\documents\ergonomyx\ergonomyx-ecommerce\venv\lib\site-packages\hubspot\auth\oauth\api\default_api.py", line 20, in <module>
    from hubspot.auth.oauth.api_client import ApiClient
  File "c:\users\hector\documents\ergonomyx\ergonomyx-ecommerce\venv\lib\site-packages\hubspot\auth\oauth\api_client.py", line 15, in <module>
    from dateutil.parser import parse
File "c:\users\hector\documents\ergonomyx\ergonomyx-ecommerce\venv\lib\site-packages\dateutil\parser.py", line 158
    l.append("%s=%s" % (attr, `value`))

**Comment by HectorGit** [comment]
Hi I found a solution !

* pip3 uninstall python-dateutil 

(I use pip3 because I'm inside a python3 virtual environment) 

luckily, we were no longer using this in our application , but for some reason it causes trouble. 

Hopefully this will help others that run into this issue.

**Comment by HectorGit** [comment]
Oh yeah ! And remember to remove it from any import statements, as well as the requirements.txt
